python learning.py -m 32 -l "images"
python learning.py -m 256 -l "images"
python learning.py -m 32 -l "landmarks"
python learning.py -m 256 -l "landmarks"
python learning.py -m 32 -l "images_landmarks"
python learning.py -m 256 -l "images_landmarks"